version: '3'
services:
  mysql-master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    links:
      - mysql-slave
    ports:
      - "33065:3306"
    restart: always
    hostname: mysql-master
    container_name: mysql-master
    volumes:
      - ./data/mysql/master:/var/lib/mysql
  mysql-slave:
    build:
      context: ./
      dockerfile: slave/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "33066:3306"
    restart: always
    hostname: mysql-slave
    container_name: mysql-slave
    volumes:
      - ./data/mysql/slave:/var/lib/mysql
